import { BiSolidStar } from "react-icons/bi";
import { BiSolidStarHalf } from "react-icons/bi";
import { BiStar } from "react-icons/bi";


export const featureListingsData = [
    {
      flImg: "/assets/images/car2.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 1,
      numberOfImages: 5,
      featured: true,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 1,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "sophia.jones@example.com",
    description: "Labore commodo duis magna irure sint incididunt nisi laborum anim. Nostrud eiusmod non excepteur ullamco laboris magna sit et exercitation est cupidatat. Esse pariatur enim ut sint ex. Exercitation nostrud esse et officia nostrud. Veniam eiusmod officia commodo veniam ex id magna Lorem commodo. Velit voluptate ex culpa veniam deserunt non fugiat nostrud enim ex. Non cupidatat magna cupidatat ut veniam. Do elit labore sint qui Lorem Lorem. Ut quis ad dolor ex. Laboris cupidatat sint fugiat amet aliqua dolore irure proident mollit sint officia veniam Lorem ea. Adipisicing et tempor consectetur laborum nisi laborum sit ut qui aliquip. Aute ullamco magna irure anim officia consectetur ut elit. Consequat laboris mollit mollit Lorem anim tempor eu ut. Fugiat laboris enim sit eiusmod ex excepteur qui exercitation ut non ullamco excepteur minim. Deserunt ex magna cupidatat laborum officia sunt magna et.",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Emma Thompson",
          date: "January 1, 2022",
          stars: [1, 1, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Oliver Davis",
          date: "August 6, 2020",
          stars: [1, 1, 0, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car1.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 2,
      numberOfImages: 5,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 2,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "oliver.miller@example.com",
    description: "Nisi non aliqua do velit dolor. Velit exercitation dolor mollit ullamco non officia dolor deserunt quis ipsum. Veniam nulla occaecat exercitation sit deserunt mollit nisi. Tempor sit aliqua proident occaecat cillum elit consectetur commodo ut minim non deserunt. Cupidatat nostrud amet officia aliquip velit magna dolore ex excepteur incididunt aliqua est laborum. Do voluptate ea minim dolor cupidatat non labore magna incididunt. Amet aute eu labore ipsum pariatur sint. Do Lorem veniam fugiat irure exercitation consequat qui nisi in ad consequat magna. Velit amet eu ut sunt consectetur fugiat laboris dolore laboris quis id. Nostrud mollit incididunt ea eu sunt aute ad minim exercitation minim veniam. Esse nostrud irure ut ut pariatur enim. Ullamco mollit adipisicing laboris excepteur.",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car2.jpg",
          name: "Habiba Abdulrazaq",
          date: "November 3, 2022",
          stars: [1, 0, 0.5, 1, 0.5],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car2.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 3,
      numberOfImages: 5,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 3,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Sophia Martinez",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Liam Johnson",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car1.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 4,
      numberOfImages: 5,
      featured: true,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 4,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car2.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 5,
      numberOfImages: 3,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 5,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car1.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 6,
      numberOfImages: 2,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 6,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car2.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 7,
      numberOfImages: 4,
      featured: true,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 7,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
    },
    {
      flImg: "/assets/images/car1.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 8,
      numberOfImages: 5,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 8,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
    },
    {
      flImg: "/assets/images/car1.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 9,
      numberOfImages: 5,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 9,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car2.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 10,
      numberOfImages: 3,
      featured: true,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 10,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car2.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 11,
      numberOfImages: 5,
      featured: true,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 1,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      flImg: "/assets/images/car1.jpg",
      flAmount: 2500,
      flTitle: "BMW M4 G82 - 2021",
      FL_: 12,
      numberOfImages: 5,
      featured: false,
      flReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      numberOfReviews: 2,
      mileage: 1500,
      fuelType: "Petrol",
      transmission: "Manual",
      category: "All Status",
      contact: "john@example.com",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
    duration: "2026",
    address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
  ];
