import { SlPhone } from "react-icons/sl";
import { SlLocationPin } from "react-icons/sl";
import { AiOutlineClockCircle } from "react-icons/ai";
import { TiSocialFacebook } from "react-icons/ti";
import { TiSocialTwitter } from "react-icons/ti";
import { LiaInstagram } from "react-icons/lia";
import { TiSocialLinkedin } from "react-icons/ti";
import { IoMdArrowDropdown } from "react-icons/io";
import { BiSolidStar } from "react-icons/bi";
import { BiSolidStarHalf } from "react-icons/bi";
import { BiStar } from "react-icons/bi";


export const newCarsData = [
    {
      ncImg: "/assets/images/car1.jpg",
      ncAmount: 2500,
      ncTitle: "BMW M4 G82 - 2021",
      NC_: 1,
      ncNumberOfImages: 5,
      ncFeatured: true,
      ncReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ncNumberOfReviews: 2,
      ncMileage: 1500,
      ncFuelType: "Petrol",
      ncTransmission: "Manual",
      ncCategory: "New",
      contact: "oliver.miller@example.com",
      description: "Qui ipsum quis do id eiusmod tempor amet irure ad magna. Ullamco fugiat occaecat cillum in dolore. Consectetur exercitation laborum veniam commodo do ut. Laboris tempor eu ullamco tempor minim anim dolore ut labore. Nostrud velit anim dolore eiusmod sit. Nostrud do aute reprehenderit sint sint sint voluptate ut eiusmod sint. Aute excepteur dolore ex ad laboris in consequat eu ullamco cillum nulla esse excepteur id. Sint excepteur ut nisi aliqua officia. Aliquip deserunt consequat in exercitation Lorem est pariatur aliquip cupidatat nulla deserunt. Cupidatat dolore minim deserunt est laborum labore pariatur occaecat amet laboris cupidatat.",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          NC_: 1,
          photo: "/assets/images/car1.jpg",
          name: "Noah Brown",
          date: "July 5, 2021",
          stars: [1, 0, 1, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          NC_: 2,
          photo: "/assets/images/car2.jpg",
          name: "Isabella Wilson",
          date: "February 28, 2023",
          stars: [0.5, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ncImg: "/assets/images/car1.jpg",
      ncAmount: 2500,
      ncTitle: "BMW M4 G82 - 2021",
      NC_: 2,
      ncNumberOfImages: 5,
      ncFeatured: true,
      ncReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ncNumberOfReviews: 2,
      ncMileage: 1500,
      ncFuelType: "Petrol",
      ncTransmission: "Manual",
      ncCategory: "New",
      ncContact: "ava.jackson@example.com",
      ncDescription: "Officia in nulla sint in dolor exercitation. Exercitation deserunt occaecat cillum laboris. Et mollit tempor quis nostrud adipisicing cupidatat fugiat consequat consequat aliqua in aliqua exercitation laborum. Reprehenderit occaecat fugiat quis nulla do magna exercitation non deserunt labore cillum. Exercitation aliquip deserunt nisi ex ea dolore. Veniam et ad ut elit incididunt sint fugiat exercitation commodo eiusmod nulla. Cupidatat mollit aute sint ullamco irure et incididunt anim sint magna irure enim eiusmod minim. Laborum ex nostrud cupidatat excepteur laboris eu. Velit adipisicing ea quis qui amet reprehenderit esse anim occaecat sint est ullamco. Quis tempor anim minim nostrud reprehenderit pariatur labore nulla anim velit duis do irure laborum. Cupidatat irure ullamco fugiat cillum elit enim nostrud Lorem ipsum cillum aliqua sint quis pariatur.",
      ncDuration: "2026",
      ncAddress: "1101 W Anaheim St, Wilmington, CA",
    ncOverview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    ncFeatures: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    ncReviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Ethan Miller",
          date: "June 16, 2019",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Mia Jones",
          date: "March 13, 2022",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ncImg: "/assets/images/car1.jpg",
      ncAmount: 2500,
      ncTitle: "BMW M4 G82 - 2021",
      NC_: 3,
      ncNumberOfImages: 5,
      ncFeatured: true,
      ncReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ncNumberOfReviews: 2,
      ncMileage: 1500,
      ncFuelType: "Petrol",
      ncTransmission: "Manual",
      ncCategory: "New",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ncImg: "/assets/images/car1.jpg",
      ncAmount: 2500,
      ncTitle: "BMW M4 G82 - 2021",
      NC_: 4,
      ncNumberOfImages: 5,
      ncFeatured: true,
      ncReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ncNumberOfReviews: 2,
      ncMileage: 1500,
      ncFuelType: "Petrol",
      ncTransmission: "Manual",
      ncCategory: "New",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ncImg: "/assets/images/car1.jpg",
      ncAmount: 2500,
      ncTitle: "BMW M4 G82 - 2021",
      NC_: 5,
      ncNumberOfImages: 5,
      ncFeatured: true,
      ncReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ncNumberOfReviews: 2,
      ncMileage: 1500,
      ncFuelType: "Petrol",
      ncTransmission: "Manual",
      ncCategory: "New",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ncImg: "/assets/images/car1.jpg",
      ncAmount: 2500,
      ncTitle: "BMW M4 G82 - 2021",
      NC_: 6,
      ncNumberOfImages: 5,
      ncFeatured: true,
      ncReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ncNumberOfReviews: 2,
      ncMileage: 1500,
      ncFuelType: "Petrol",
      ncTransmission: "Manual",
      ncCategory: "New",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
  ];