import { SlPhone } from "react-icons/sl";
import { SlLocationPin } from "react-icons/sl";
import { AiOutlineClockCircle } from "react-icons/ai";
import { TiSocialFacebook } from "react-icons/ti";
import { TiSocialTwitter } from "react-icons/ti";
import { LiaInstagram } from "react-icons/lia";
import { TiSocialLinkedin } from "react-icons/ti";
import { IoMdArrowDropdown } from "react-icons/io";
import { BiSolidStar } from "react-icons/bi";
import { BiSolidStarHalf } from "react-icons/bi";
import { BiStar } from "react-icons/bi";


export const usedCarsData = [
    {
      ucImg: "/assets/images/car2.jpg",
      ucAmount: 2500,
      ucTitle: "BMW M4 G82 - 2021",
      UC_: 1,
      ucNumberOfImages: 5,
      ucFeatured: true,
      ucReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ucNumberOfReviews: 2,
      ucMileage: 1500,
      ucFuelType: "Petrol",
      ucTransmission: "Manual",
      ucCategory: "Used",
      contact: "david.wilson@example.com",
      description: "Veniam non duis occaecat est do aliquip sint nostrud magna ad officia laborum do. Occaecat reprehenderit deserunt ut et exercitation enim nostrud consequat. Eiusmod reprehenderit aliquip duis duis exercitation laborum ad ad ullamco id reprehenderit id. Sint laborum ipsum eiusmod aliqua nulla aliquip reprehenderit esse deserunt id do quis tempor aliqua. Dolor sunt minim amet magna consectetur incididunt officia deserunt magna quis. Velit velit laborum anim tempor ea officia exercitation incididunt mollit cupidatat fugiat nulla. Cillum ullamco culpa consectetur reprehenderit minim eiusmod veniam commodo. Proident incididunt consequat aute non commodo velit laboris ipsum nisi aliqua. Nulla velit laborum ex eiusmod labore cillum ad aute consequat sint anim ea mollit magna. Sit velit tempor ad nisi aute incididunt cillum nulla veniam deserunt consequat excepteur nulla ut. Deserunt in deserunt magna laboris pariatur ex. Dolor do ipsum sit id elit. Duis dolor nulla quis do enim. Aliqua non esse id sint deserunt dolore anim proident.",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car2.jpg",
          name: "Lucas Anderson",
          date: "January 9, 2017",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car1.jpg",
          name: "Amelia Thomas",
          date: "August 19, 2021",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ucImg: "/assets/images/car2.jpg",
      ucAmount: 2500,
      ucTitle: "BMW M4 G82 - 2021",
      UC_: 2,
      ucNumberOfImages: 5,
      ucFeatured: true,
      ucReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ucNumberOfReviews: 2,
      ucMileage: 1500,
      ucFuelType: "Petrol",
      ucTransmission: "Manual",
      ucCategory: "Used",
      contact: "emma.smith@example.com",
      description: "Magna magna occaecat est in. Commodo tempor irure ullamco minim sunt sint anim nulla eiusmod laborum aute culpa dolore enim. Enim mollit elit qui cillum nulla fugiat Lorem ea. Voluptate laboris et irure esse. Amet sunt et non cillum aute culpa deserunt duis. Pariatur do elit amet enim adipisicing fugiat et id non occaecat aliquip laboris excepteur. Nulla commodo cillum consectetur consequat est proident labore minim consequat. Nulla minim cillum elit deserunt occaecat. Ullamco laborum officia ea commodo laboris aute deserunt aliqua. Eu enim voluptate Lorem minim labore reprehenderit mollit minim cupidatat dolore cillum. Cillum aute qui ullamco adipisicing adipisicing id minim eu sint aute. Qui pariatur consectetur sit aliquip ipsum pariatur nostrud eu sunt ex consequat consequat consequat fugiat. Proident commodo adipisicing sit duis ex cupidatat nulla aliquip culpa nulla cillum consectetur fugiat. Sit sit excepteur dolor do sunt consectetur quis.",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Aiden White",
          date: "January 12, 2023",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Alexander Garcia",
          date: "May 23, 2023",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ucImg: "/assets/images/car2.jpg",
      ucAmount: 2500,
      ucTitle: "BMW M4 G82 - 2021",
      UC_: 3,
      ucNumberOfImages: 5,
      ucFeatured: true,
      ucReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ucNumberOfReviews: 2,
      ucMileage: 1500,
      ucFuelType: "Petrol",
      ucTransmission: "Manual",
      ucCategory: "Used",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ucImg: "/assets/images/car2.jpg",
      ucAmount: 2500,
      ucTitle: "BMW M4 G82 - 2021",
      UC_: 4,
      ucNumberOfImages: 5,
      ucFeatured: true,
      ucReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ucNumberOfReviews: 2,
      ucMileage: 1500,
      ucFuelType: "Petrol",
      ucTransmission: "Manual",
      ucCategory: "Used",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ucImg: "/assets/images/car2.jpg",
      ucAmount: 2500,
      ucTitle: "BMW M4 G82 - 2021",
      UC_: 5,
      ucNumberOfImages: 5,
      ucFeatured: true,
      ucReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ucNumberOfReviews: 2,
      ucMileage: 1500,
      ucFuelType: "Petrol",
      ucTransmission: "Manual",
      ucCategory: "Used",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
    {
      ucImg: "/assets/images/car2.jpg",
      ucAmount: 2500,
      ucTitle: "BMW M4 G82 - 2021",
      UC_: 6,
      ucNumberOfImages: 5,
      ucFeatured: true,
      ucReviews: [
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStar />,
        },
        {
          reviewIcon: <BiSolidStarHalf />,
        },
        {
          reviewIcon: <BiStar />,
        },
      ],
      ucNumberOfReviews: 2,
      ucMileage: 1500,
      ucFuelType: "Petrol",
      ucTransmission: "Manual",
      ucCategory: "Used",
      contact: "john@example.com",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...",
      duration: "2026",
      address: "1101 W Anaheim St, Wilmington, CA",
    overview: {
      type: "Compact",
      make: "Toyota",
      model: "Corolla",
      color: "Silver",
      driveType: "Front-Wheel Drive",
      transmission: "Automatic",
      condition: "Used",
      year: 2018,
      mileage: 50000,
      fuelType: "Gasoline",
      engineSize: "2.0L",
      door: 4,
      cylinder: 4,
      vin: "ABC123456789",
    },
    features: {
      convenience: [
        "Heated Seats",
        "Heated Steering Wheel",
        "Navigation System",
        "Tyre Pressure Monitoring System",
      ],
      entertainment: ["Apple CarPlay/Android Auto", "Bluetooth", "HomeLink"],
      safety: [
        "Airbag - Driver",
        "Airbag - Passenger",
        "Anti-lock Braking System",
        "Backup Camera",
        "Blind Spot Monitor",
      ],
      interior: [
        "Center Console",
        "Heated and Ventilated Front Seats",
        "Panoramic Moonroof",
        "Qi Wireless Charging",
      ],
      exterior: [
        "Alloy Wheels",
        "Brake Calipers - Silver Painted",
        "Rear Bumper High Gloss",
        "Rear Diffuser Body Colour",
      ],
    },
    reviewData: {
      featureReviews: [
        { reviewName: "Comfort", reviewRating: 4.5 },
        { reviewName: "Interior Design", reviewRating: 4.5 },
        { reviewName: "Performance", reviewRating: 4.5 },
        { reviewName: "Value for the money", reviewRating: 4.0 },
        { reviewName: "Exterior styling", reviewRating: 4.0 },
        { reviewName: "Reliability", reviewRating: 4.0 },
      ],
      reviewComments: [
        {
          photo: "/assets/images/car1.jpg",
          name: "Habiba Abdulrazaq",
          date: "January 1, 2022",
          stars: [1, 0, 0.5, 1, 1],
          comment: "Eiusmod esse Lorem irure ullamco cillum. Amet est Lorem nulla commodo voluptate amet esse ea eu sunt eu amet do. Culpa adipisicing commodo ad exercitation. Exercitation adipisicing incididunt aute commodo ea nisi esse incididunt et cillum aliqua dolore. Aliqua cupidatat magna id quis cupidatat. Quis exercitation aliqua veniam commodo.",
        },
        {
          photo: "/assets/images/car2.jpg",
          name: "Musa Abdulmuqaddas",
          date: "August 6, 2020",
          stars: [1, 1, 1, 1, 0.5],
          comment: "Culpa fugiat eiusmod quis do voluptate consectetur irure mollit consectetur. Dolor ipsum officia consequat non do. Commodo sint quis ut dolor incididunt nostrud minim ipsum. Culpa officia tempor proident ad labore eiusmod id fugiat veniam ad nulla esse. Cillum ad est non enim dolor et.",
        },
      ],
    },
    },
  ];
  